flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- exceptions-0.8.0.2
- hashable-1.2.3.3
- hscurses-1.4.2.0
- mtl-2.2.1
- nats-1
- random-1.1
- semigroups-0.16.2.2
- stm-2.4.4
- text-1.2.1.1
- transformers-0.4.3.0
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
resolver: ghc-7.8
